name: test

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  test:
    name: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: config conda and install
        shell: bash -l {0}
        run: |
          conda config --set always_yes True
          conda install --file requirements/run.txt --file requirements/tests.txt pip
          python -m pip install git+https://github.com/regro/libcflib.git
          python -m pip install --no-deps -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8

      - name: run tests
        shell: bash -l {0}
        run: |
          # Avoid errors like "Warning: _curses.error: setupterm: could not find terminfo database" when using pwntools
          export TERM=xterm
          pytest -v
